{% set version = "0.13.4" %}

package:
  name: bottle
  version: {{ version }}

source:
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: 807c789c3184d7070010dbdf1339ee46ff9fb9b6694d7caa3047f975f8a7df60

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org
  license: MIT
  license_file: LICENSE
  summary: Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. 
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: http://bottlepy.org/docs/0.12/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
