{% set name = "bottle" %}
{% set version = "0.12.13" %}
{% set sha256 = "c89ce532b1c180905d03a4815fea2d7b9b444f5e13407f43a9c7eae5777aa613" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org
  license: MIT
  license_file: LICENSE
  summary: 'Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.'

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. 
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: http://bottlepy.org/docs/0.12/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
