{% set name = "bottle" %}
{% set version = "0.12.19" %}
{% set sha256 = "b97277f8e87d452a0aa5fbcd16cd604a189e2cc17fdb2d4eaf6baa732f8d111b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/bottlepy/bottle/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - bottle

about:
  home: http://bottlepy.org
  license: MIT
  license_file: LICENSE
  summary: Bottle is a fast, simple and lightweight WSGI micro web-framework for Python.

  description: |
    Bottle is a fast, simple and lightweight WSGI micro web-framework for Python. 
    It is distributed as a single file module and has no dependencies other than the Python Standard Library.
  doc_url: http://bottlepy.org/docs/0.12/
  dev_url: https://github.com/bottlepy/bottle

extra:
  recipe-maintainers:
    - hajapy
    - jmeppley
